grsim_node:
  ros__parameters:
    grsim_command_listen_port: 50051
    grsim_ip: "192.168.1.50"
vision_node:
  ros__parameters:
    vision_multicast_port: 50055
    vision_multicast_ip: "224.5.23.2"
worldmodel_node:
  ros__parameters:
    is_simulation: True
    is_our_side_left: True
    is_our_color_yellow: False
    cam_num: 1
    camera_0: True
    camera_1: False
    camera_2: False
    camera_3: False
    camera_4: False
    camera_5: False
    camera_6: False
    camera_7: False
soccer_view_node:
  ros__parameters:
    active_soccer_view: False
    draw_debugs: False
agent_node:
  ros__parameters:
    P_vel: 10.0
    I_vel: 10.0
    D_vel: 10.0
    P_pos: 10.0
    I_pos: 10.0
    D_pos: 10.0
    max_vel: 4.0